# Generated by Django 2.2.1 on 2019-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('insta_id', models.IntegerField()),
                ('insta_username', models.CharField(max_length=128)),
                ('insta_link', models.URLField()),
                ('insta_image_link', models.URLField()),
                ('insta_caption', models.CharField(max_length=2048)),
            ],
        ),
    ]
